# Generated by Django 4.2.5 on 2023-09-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
